Bilan du code pour la résolution du Puzzle

Il faut d'abord créer toutes les lettres grâce à des matrices carrées (plus facile pour appliquer une rotation par la suite), qu'on va incorporer dans une grille convexe de taille n*m

In [1]:
import numpy as np

def creation_grille(n,m):
    tab = np.zeros((n,m))
    return(tab)
    
n = 6
m = 10
grille=creation_grille(n,m)

In [3]:
lettre_f=np.zeros((3,3))
lettre_f[0,1]=1
lettre_f[0,2]=1
lettre_f[1,0]=1
lettre_f[1,1]=1
lettre_f[2,1]=1

lettre_i=np.zeros((5,5))
lettre_i[0,0]=1
lettre_i[1,0]=1
lettre_i[2,0]=1
lettre_i[3,0]=1
lettre_i[4,0]=1

lettre_l=np.zeros((4,4))
lettre_l[0,0]=1
lettre_l[1,0]=1
lettre_l[2,0]=1
lettre_l[3,0]=1
lettre_l[3,1]=1

lettre_n=np.zeros((4,4))
lettre_n[0,1]=1
lettre_n[1,1]=1
lettre_n[2,1]=1
lettre_n[2,0]=1
lettre_n[3,0]=1

lettre_x = np.array([[0,1,0],[1,1,1],[0,1,0]])
lettre_y = np.array([[0,0,0,0],[0,0,0,0],[0,0,1,0],[1,1,1,1]])
lettre_z = np.array([[1,1,0],[1,1,1],[0,1,1]])
lettre_p = np.array([[1,1,0],[1,1,0],[1,0,0]])
lettre_t = np.array([[1,1,1],[0,1,0],[0,1,0]])

lettre_u = np.array([[0,0,0],
                     [1,0,1],
                     [1,1,1]])
lettre_v = np.array([[0,0,1],
                     [0,0,1],
                     [1,1,1]])
lettre_w = np.array([[0,0,1],
                     [0,1,1],
                     [1,1,0]])

dict = {'f' : lettre_f, 'i' :lettre_i, 'l' : lettre_l, 'n': lettre_n, 'p': lettre_p, 't': lettre_t, 'u' : lettre_u,'v':lettre_v, 'w': lettre_w, 'x' : lettre_x,'y' : lettre_y , 'z' : lettre_z}

Lettres_Base = [lettre_f,lettre_i,lettre_l,lettre_n,lettre_p,lettre_t,lettre_u,lettre_v,lettre_w,lettre_x,lettre_y,lettre_z]


Maintenant qu'on a nos lettres, il faut aussi obtenir leurs rotation et leurs symétries

In [24]:
def rotation(tab):
    return(np.rot90(tab,1,(0,1)))

def symetrie(tab):
    return(np.fliplr(tab))

def ensemble_rotation_symetrie(lettre):
    tab=[lettre]
    for i in range(1,4):
        x=rotation(tab[-1])
        tab.append(x)
    for j in range(0,4):
        x=symetrie(tab[i])
        tab.append(x)
    return(tab)

def Lettres_tot():
    Lettres_tot =[]
    for key in dict.keys() :
        Lettres_tot.append(ensemble_rotation_symetrie(dict[key]))
    return(Lettres_tot)

total_lettres=Lettres_tot()
print(total_lettres)

[[array([[0., 1., 1.],
       [1., 1., 0.],
       [0., 1., 0.]]), array([[1., 0., 0.],
       [1., 1., 1.],
       [0., 1., 0.]]), array([[0., 1., 0.],
       [0., 1., 1.],
       [1., 1., 0.]]), array([[0., 1., 0.],
       [1., 1., 1.],
       [0., 0., 1.]]), array([[0., 1., 0.],
       [1., 1., 1.],
       [1., 0., 0.]]), array([[0., 1., 0.],
       [1., 1., 1.],
       [1., 0., 0.]]), array([[0., 1., 0.],
       [1., 1., 1.],
       [1., 0., 0.]]), array([[0., 1., 0.],
       [1., 1., 1.],
       [1., 0., 0.]])], [array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]]), array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]]), array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]]), array([[1., 1., 1., 1., 1.],
      

Il faut incorporer ces lettres dans la grille, mais pour cela il faut d'abord réduire la matrice carrée contenant la lettre au rectangle minimal contenant la lettre

In [20]:
def reduction(Mat):
    L=[]
    K=len(Mat)
    for i in range(K):
        if sum(Mat[i]) == 0 :
            L.append(i)
    Mat=np.delete(Mat,L,0)
    L=[]
    Mat=np.transpose(Mat)
    for i in range(K):
        if sum(Mat[i]) == 0 :
            L.append(i)
    Mat=np.delete(Mat,L,0)
    return(np.transpose(Mat))

reduction_vectorise=np.vectorize(reduction)

#reduction_vectorise(total_lettres) qui ne marche pas donc on for désolé

total_lettres_reduite=[]
for x in total_lettres:
    p=[]
    for y in x:
        #print(y)
        #print(reduction(y))
        p.append(reduction(y))
    total_lettres_reduite.append(p)

total_lettres_reduite

[[array([[0., 1., 1.],
         [1., 1., 0.],
         [0., 1., 0.]]),
  array([[1., 0., 0.],
         [1., 1., 1.],
         [0., 1., 0.]]),
  array([[0., 1., 0.],
         [0., 1., 1.],
         [1., 1., 0.]]),
  array([[0., 1., 0.],
         [1., 1., 1.],
         [0., 0., 1.]]),
  array([[0., 1., 0.],
         [1., 1., 1.],
         [1., 0., 0.]]),
  array([[0., 1., 0.],
         [1., 1., 1.],
         [1., 0., 0.]]),
  array([[0., 1., 0.],
         [1., 1., 1.],
         [1., 0., 0.]]),
  array([[0., 1., 0.],
         [1., 1., 1.],
         [1., 0., 0.]])],
 [array([[1.],
         [1.],
         [1.],
         [1.],
         [1.]]),
  array([[1., 1., 1., 1., 1.]]),
  array([[1.],
         [1.],
         [1.],
         [1.],
         [1.]]),
  array([[1., 1., 1., 1., 1.]]),
  array([[1., 1., 1., 1., 1.]]),
  array([[1., 1., 1., 1., 1.]]),
  array([[1., 1., 1., 1., 1.]]),
  array([[1., 1., 1., 1., 1.]])],
 [array([[1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 1.]]),


In [ ]:
Maintenant on liste toutes les grilles possibles

In [26]:
def placement(grille,matrice):
    n,p=np.shape(grille)
    s,t=np.shape(matrice)
    liste=[]
    for i in range(n-s+1):
        for j in range(p-t+1):
            nom=np.zeros((n,p))
            nom[i:i+s,j:j+t]=matrice
            liste.append(nom)
    return liste

#placement_vectorise=np.vectorize(placement)
#placement_vectorise(grille,l)

total_lettres_reduite_placee=[]
for p in total_lettres_reduite:
    for q in p:
        total_lettres_reduite_placee.append(placement(grille,x))

total_lettres_reduite_placee

[[array([[1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
  array([[0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
  array([[0., 0., 1., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 1., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
  array([[0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1.,

Il faut transformer les matrices dans une représentation compatible avec la fonction qui va résoudre

In [ ]:
code de nico

reste plus qu'à résoudre